### ISSUE TITLE
Review CentOS/Redhat httpd.conf and httpd_2.4.conf

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#125]
Currently there is strange approach in configuring apache:
1) In Ubuntu/Debian we uses default apache2.conf
2) In CentOS/Redhat we render httpd.conf and httpd_2.4.conf

Point 2 is not very secure approach because our template is static and we can miss some major configuration updates.
Is it possible to not overwrite system httpd.conf and httpd_2.4.conf in setup?
Which custom changes we are installing in this way?

**Comment by ganesh-at-wiw** [comment]
Starting on this now.

**Comment by ganesh-at-wiw** [comment]
I've gone through the config files in detail.
At the end I came to the conclusion that keeping httpd.conf as custom is the best way.

With new versions we can incorporate different version as per distros.

In Ubuntu, the approach is different. Their the modules are totally separate from apache2.conf. So, there it's possible to use default apache2.conf. But in CentOS, the httpd.conf loads lots of modules by default. Then, to lighten up apache config, we've to make changes to httpd.conf. So, instead of making changes to new httpd.conf, we can incorporate the changes from new httpd.conf in our httpd.conf. This way or other, it's going to be same.

So, I propose to keep the present approach about httpd.conf as such.
