### ISSUE TITLE
Remove IDP2 from CE

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#194]

**Comment by uboznikov** [comment]
@yurem Can we not bundle idp.war in /etc/dist/war? This war is from IDP 2, and wget could not seem to overwrite it. I removed this before I run setup.py and the "Caused by: java.io.FileNotFoundException: /opt/idp/conf/internal.xml (No such file or directory)" error went away. And also if all other IDP wars not be bundled because these are being downloaded when IDP is chosen to be installed. Other options are most welcome. Thanks.

**Comment by uboznikov** [comment]
Screenshot of /opt/dist/war from latest binary 11/7/2016, with old IDP war

![old-idp-war](https://cloud.githubusercontent.com/assets/16329085/20102694/f858135c-a601-11e6-8b2b-89439b8c8808.png)

**Comment by yurem** [comment]
Done!
