### ISSUE TITLE
import244.py throwing error

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#221]
OS: CentOS6.x

```
GLUU.[root@localhost ~]# ./import244.py backup_24/
Traceback (most recent call last):
  File "./import244.py", line 531, in <module>
    main(sys.argv[1])
  File "./import244.py", line 472, in main
    backup_version = int(getBackupProperty('version').replace('.', '').strip()[:3])
ValueError: invalid literal for int() with base 10: 'sp2'
GLUU.[root@localhost ~]#
```

**Comment by tecoholic** [comment]
Ok. this has got something to do with the version containing the literals sp2. The script was written to handle just three digit dot separated version strings. It will be updated to include the new scheme of four digit and string based  versions as well.

**Comment by tecoholic** [comment]
@mzico I tested on the following strings for version names. All of the below pass the integer conversion `int(getBackupProperty('version').replace('.', '').strip()[:3])`

```
'2.3.6'
'2.4.0\n'
' 2.4.3\n'
'2.4.4.2'
'2.4.4.2 \n'
'2.4.4.sp2 \n'
'2.4.4-sp2'
```

Is there a version defined which start with the string `sp2` instead the dot separated integer notation? Because the only way the reported error could have arisen is when there is a line in `setup.properties` which is similar to `version= sp2.x.x.`. Does the installation of service packs create a line like that in setup.properties?

**Comment by mzico** [comment]
>> Is there a version defined which start with the string sp2 instead the dot separated integer notation? 

Looping @yurem .
