### ISSUE TITLE
Update OpenDJ

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#401]
On our [OpenDJ repo](https://github.com/GluuFederation/gluu-opendj3)

`This branch is 233 commits ahead, 30 commits behind OpenRock:master.`

Should we look at those 30 commits?

**Comment by yurem** [comment]
yes, we can try to update code in our repo and rebuild it

**Comment by yurem** [comment]
Finally I find way to [build ](https://ox.gluu.org/jenkins/job/gluu-opendj3/40/console) it! Here is new [dist](http://ox.gluu.org/maven/org/forgerock/opendj/opendj-server-legacy/3.0.0.1.gluu/opendj-server-legacy-3.0.0.1.gluu.zip).

@aliaksander-samuseu @mzico @sahiliamsso If you have time for this can you try to install 3.1.2 with this OpenDJ build? We need to check if we can include this version into 3.1.3.
Before running setup you can replace OpenDJ zip in /opt/dist.. to use this built.

**Comment by yurem** [comment]
From my point of view this 3.0.0.Final has bugs.
I can't use our attributes as DN member values, etc..

Here is what I get:
![image](https://user-images.githubusercontent.com/6104200/36585236-1a174332-188e-11e8-87d4-608d9e95556b.png)

I did next testing:
1. Remove all our custom schema files.
2. Add new schema file:
```
dn: cn=schema
objectClass: top
objectClass: ldapSubentry
objectClass: subschema
attributeTypes: ( 0.9.2342.19200300.500.1.1 NAME ( 'newuid' )
  EQUALITY caseIgnoreMatch SUBSTR caseIgnoreSubstringsMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.15{256} X-ORIGIN 'RFC 4519' )
objectClasses: ( 1.3.6.1.4.1.9923.1.1.2 NAME 'test' STRUCTURAL MAY ( newuid ) 
  X-ORIGIN 'Test OC' )
```
3. Restart OpenDJ
4. Create new backend
5. Load into it next ldif:
```
version: 1

dn: o=check
objectClass: organization
objectClass: top
o: check

dn: ou=people,o=check
objectClass: organizationalUnit
objectClass: top
ou: people

dn: ou=group,o=check
objectClass: organizationalUnit
objectClass: top
ou: group

dn: cn=test,ou=group,o=check
objectClass: top
objectClass: groupOfNames
cn: test

dn: uid=user_uid,ou=people,o=check
objectClass: inetOrgPerson
objectClass: person
objectClass: top
objectClass: organizationalPerson
cn: User
sn: User
uid: user_uid

dn: newuid=user_newuid,ou=people,o=check
objectClass: person
objectClass: test
objectClass: top
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: User
sn: User
newuid: user_newuid

```

6. Add to cn=test,ou=group,o=check attribute `member` with value `uid=user_uid,ou=people,o=check`
7. Add to cn=test,ou=group,o=check attribute `member` with value `newuid=user_newuid,ou=people,o=check`

At step 7 I got error which I mentioned above.

I'm closing this. Please re-open if needed. Due to bug about setup also not works.
