### ISSUE TITLE
Authentication scripts' levels need to be updated

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/community-edition-setup#431]
According to @yurem , values of "Level" property of custom authentication scripts pre-packaged in Gluu's packages don't mirror the current model, but the previous one ("the greater the level, the less it's secure" instead of "the greater the level, the more it's secure"). For example, "basic" has level of 100, while "u2f" is just at 10.

**Comment by yurem** [comment]
I offer to review `level` in new major release. I think we should not change this behavior between 3.1.x version. Maybe some of users uses backward order level already.

**Comment by willow9886** [comment]
yea, greater level should indicate more security. Perhaps we can make this configurable though, in order to maintain any backwards compatibility?

**Comment by yurem** [comment]
Fixed

**Comment by ldeveloperl1985** [comment]
I have tested this in `gluu-server-4.0_1-59~xenial+Ub16.04_amd64.deb`, it is not working as level configuration.

Configuration:
Both scripts are enabled and updated the level so `OTP = 60 level and U2F = 50 level`
![Screenshot (1)](https://user-images.githubusercontent.com/2329776/60269691-93cf3b80-990c-11e9-8e70-7d3e071704cc.png)

My auth request is 
```
https://gluu.local.org/oxauth/restv1/authorize?response_type=code&client_id=28275837-c059-4116-
b91e-
8a11b5b265bb&redirect_uri=https://gluu.local.org:8443/callback&scope=openid+oxd+email+profile+uma
_protection+permission&state=h2bf5dna4oqcjvq54n9skv65a3&nonce=ubnamt33pqhmsjfus7hvj7d8m2&
acr_values=u2f+otp
```

Expected behavior:
Gluu CE should provide the **OTP** auth because its level is **60**

Current behavior: 
Currently, Gluu CE provides auth which first appears in acr_values `acr_values=u2f+otp` value in the auth request i.e. **u2f**.
If I changed the order `acr_values=otp+u2f` then it goes for OTP Auth.

Environment:
OS: Ub16
Gluu CE: gluu-server-4.0_1-59~xenial+Ub16.04_amd64.deb

logs:

[oxauth.log](https://github.com/GluuFederation/community-edition-setup/files/3334971/oxauth.log)
[oxd-server.log](https://github.com/GluuFederation/community-edition-setup/files/3334966/oxd-server.log)
