### ISSUE TITLE
OpenLDAP enabled Gluu to OpenDJ-Gluu upgrade: ldap search filter not updating 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/community-edition-setup#439]
This issue is prohibiting Shibb to grab attribute's value through `siteLDAP` data connector at the time of SAML SSO. 

After upgrade ( from OpenLDAP to OpenDJ ), `idp.attribute.resolver.LDAP.searchFilter` value is intact ( which is [(uid={user})] ) which doesn't work with OpenDJ. 
For OpenDJ we need filter like this: `(|(uid=$requestContext.principalName)(mail=$requestContext.principalName))` 

Details of the problem and resolution is stated here: https://github.com/GluuFederation/support-docs/blob/master/troubleshooting/shibboleth/no_attribute_releasing_SSO.md

**Comment by mbaser** [comment]
I migrated 3.1.0 openldap to 3.1.3 opendj, idp is not working

**Comment by natt-tester** [comment]
I followed the steps provided by @mbaser:

1) install any Gluu 3.x < 3.1.2
2) while running setup.py say “Yes” to question “Install Shibboleth SAML IDP?”
3) after setup explore file /opt/shibboleth-idp/conf/ldap.properties, see this variable:
idp.attribute.resolver.LDAP.searchFilter value should be (uid={user})

Now Migrate, follow this to migrate: https://gluu.org/docs/ce/upgrade/#upgrade-from-30x-to-313
4) Do export data on current
5) install 3.1.3 (with opendj)
6) Do import
7) See if value of idp.attribute.resolver.LDAP.searchFilter changed to (|(uid=$requestContext.principalName)(mail=$requestContext.principalName))

and can confirm that the value is updated:

<img width="856" alt="success_fixed" src="https://user-images.githubusercontent.com/38302725/44319896-16cc6d80-a482-11e8-9340-44b739a6765f.png">

There were some errors during the whole process:
![errors_typo](https://user-images.githubusercontent.com/38302725/44320353-e934f380-a484-11e8-979a-bd1d9e213344.png)

![no_authentication](https://user-images.githubusercontent.com/38302725/44320345-df12f500-a484-11e8-8646-eba992ce4a0a.png)

Are they known?

**Comment by mbaser** [comment]
About warnings:
1) `/opt/opendj/db/* mount point not found` we face this warning every time, don't know reason, it has no effect
2) `Passport strategies detected` This is my warning. If there is any passport strategies, admin may enabled to login via passport. But we don't import admin user from previous system and we always set authentication method to ldap in case there is some issue so that admin can login via ldap
3) 'GPG Error` and `The following packages cannot be authenticated` This warning is not related to migration process, it is totally due to repo.gluu.org's gpg key.
