### ISSUE TITLE
rename  uma_client_authz_rpt_policy to scim_access_policy

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/community-edition-setup#444]
The name of the default policy for scope `SCIM Access` is `uma_client_authz_rpt_policy`

A better name for this policy would be `scim_access_policy`

I think we just need to update the ldif for the interception script and the UMA scope.

**Comment by sahiliamsso** [comment]
![image](https://user-images.githubusercontent.com/21104811/44177854-52c3a380-a10d-11e8-962e-5d8d10bccd5c.png)
 dont see changes in the latest war file

**Comment by jgomer2001** [comment]
@nynymike  `uma_client_authz_rpt_policy` is used by both SCIM and passport...

**Comment by mbaser** [comment]
@jgomer2001 what is your suggestion?

**Comment by jgomer2001** [comment]
This policy grants access based on a predefined list of client IDs set in config property of the cust script. If the client involved in the call is part of the list, access is simply granted…

So it's a generic script not tied to particular usage. IMO, original name `uma_client_authz_rpt_policy` is good since it fits well to the problem it solves

**Comment by afroDC** [comment]
I agree with @jgomer2001 . Should we change this scripts name if it does more than just SCIM, @nynymike ?

**Comment by nynymike** [comment]
`scim_access_policy` would be more descriptive. No need for my +1 on stuff like this :-)

**Comment by afroDC** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/76f19fc134916ea0efccdd08ccb0cea2ac144413
