### ISSUE TITLE
oxAuth service restart kill oxTrust

### ISSUE THREAD

**Issue by yurem** [GluuFederation/community-edition-setup#558]
Steps to reproduce:
1. Install CE with oxAuth/oxTrust
2. Log into console
3. Run `service oxauth restart`
4. Check if oxTrust is working after that.

**Comment by ganesh-at-wiw** [comment]
It's not bug @yurem .
Reason: oxtrust depends upon service oxauth running.
So, when oxauth is stopped, it stops oxtrust as well. Because oxtrust is dependent upon oxauth.
Since oxauth is not dependent upon oxtrust, so restarting oxtrust won't start oxtrust service.
Hence, oxtrust needs to be started manually.

**Comment by yurem** [comment]
We need to find out solution to get expected result.I think this behavior is not right. Even if restart both services needed why we not start identity?

**Comment by ganesh-at-wiw** [comment]
Two solutions:
First. Make each service independent.
Second. Restart oxauth and start identity as well.

Choice is yours unless you have some other idea.

**Comment by yurem** [comment]
I vote for First:
>> Make each service independent.

**Comment by ganesh-at-wiw** [comment]
@yurem it worked for me in new beta.
Can you also check and comment?

**Comment by ganesh-at-wiw** [comment]
Ok, closing now. Please re-open if you face problem in further tests.
