### ISSUE TITLE
Make sure default 404 page from jetty is not returned.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/community-edition-setup#626]
## Describe the issue

Mike:
We need to make sure default 404 page from jetty is not returned.

![image](https://user-images.githubusercontent.com/2013070/68036265-fd51c300-fccd-11e9-95b2-454872e9a85b.png)

That exposed info about the Jetty verison, which is a securty problem.
We should return branded error page which customer can customize.

**Comment by mbaser** [comment]
Fixed by commits:
https://github.com/GluuFederation/community-edition-setup/commit/c902c24d645cd75625e88a186306ab3298372a15
https://github.com/GluuFederation/community-edition-setup/commit/c902c24d645cd75625e88a186306ab3298372a15

![Screenshot_2019-12-31_14-33-20](https://user-images.githubusercontent.com/6398752/71620365-a9cef900-2bda-11ea-8220-266c0af929af.png)
