### ISSUE TITLE
Add /monitor endpoint for service health checks

### ISSUE THREAD

**Issue by shmorri** [GluuFederation/community-edition-setup#644]
Customers often ask about endpoints that can be used for health checks for all services. We should add a `/monitor` endpoint that can easily check their status. 

@yurem suggested the following options:
- Simple lightweight rest based ot servler based application (war)
- cgi-bin python script
- light python or node based server.
This new service should be deployed by setup ( in enterprise edition to each server). It should gather status information about all installed services and return to client

**Comment by mbaser** [comment]
This application can be written with Gunicorn: https://gunicorn.org/
It is has no dependency on Ubuntu and CentOS containers, very light and extremely fast

**Comment by mbaser** [comment]
We can combine this issue and https://github.com/GluuFederation/community-edition-setup/issues/102

**Comment by mbaser** [comment]
We have health check for all servers. A minimalist web application can both serve:
(1) As viewing health status of servers on `/monitor`
(2) And if server fails, starts automatically, and display `stderr` on web ui in case flailed to start

We can both use gunicron and bottlepy for this project. gunicorn is a general purpose wsgi web servers, whereas bottlepy is a single file and single threaded web framework. gunicorn needs installation of pypi package, but bottlepy does not. In my opinion bottlepy can be used for this project since `/monitor` endpoint won't need multiple access.
